-- KIE Models Seed SQL
-- Auto-generated from kie_models.json
-- Total: 87 models

CREATE TABLE IF NOT EXISTS ai_models (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  category TEXT NOT NULL DEFAULT 'chat',
  status TEXT NOT NULL DEFAULT 'active',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_new INTEGER NOT NULL DEFAULT 0,
  is_hot INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kimi-k3', 'Kimi K3', 'Frontier coding, native vision and 1M-token agents from Moonshot AI''s Kimi K3 — affordable API access on Kie.ai.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/custom-page/akr/section-images/1760352550893x3wzqgla.webp', 'chat', 'active', 1, 1, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-fable-5', 'Claude Fable 5', 'Claude Fable 5 is Anthropic’s Mythos-class model for advanced general use, built for long-running coding, complex knowledge work, vision reasoning, and multi-step tasks that require stronger planning ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1781069980997_fBKsGjQQ.webp', 'chat', 'active', 2, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-haiku-4-5', 'Claude Haiku 4.5', 'Claude Haiku 4.5 is Anthropic’s lightweight AI model designed for fast, cost-efficient AI applications. It delivers near-frontier performance for coding, chat, and automation tasks while providing sig', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1773393758446_zPGLzne5.png', 'chat', 'active', 3, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-opus-4-5', 'Claude Opus 4.5', 'Claude Opus 4.5 is Anthropic’s most intelligent model, combining maximum capability with practical performance across reasoning, coding, and complex problem solving.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1768360466014_sFpsHAs0.webp', 'chat', 'active', 4, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-opus-4-6', 'Claude Opus 4.6', 'Claude Opus 4.6 is Anthropic’s upgraded Opus-class model for coding, long-context reasoning, agentic workflows, and complex knowledge work, with stronger debugging, better code review, and more reliab', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1773625008611_Z4qCH1bA.webp', 'chat', 'active', 5, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-opus-4-7', 'Claude Opus 4.7', 'Claude Opus 4.7 delivers stronger agentic coding, sharper visual understanding, precise instruction following, and sustained reasoning for complex professional tasks requiring reliability, context awa', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1783586941735_IX6A2qyk.png', 'chat', 'active', 6, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-opus-4-8', 'Claude Opus 4.8', 'Claude Opus 4.8 delivers a major upgrade in complex reasoning, agentic coding, and professional knowledge work. With improved honesty, stronger long-horizon task execution, and a 1-million-token conte', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1780043083924_BXxIgbhe.png', 'chat', 'active', 7, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-sonnet-4-5', 'Claude Sonnet 4.5', 'Developed by Anthropic, Claude Sonnet 4.5 is a premier large language model that excels in multi-step reasoning, complex coding, computer use, and specialized domains such as finance.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1768545037135_d0pa2Qev.png', 'chat', 'active', 8, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-sonnet-4-6', 'Claude Sonnet 4.6', 'Claude Sonnet 4.6 delivers strong reasoning, advanced coding capabilities, and native computer-use functionality. With adaptive thinking and a context window of up to 1 million tokens, it supports bui', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1773626683685_cHZrRQVm.webp', 'chat', 'active', 9, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('claude-sonnet-5', 'Claude Sonnet 5', 'The Claude Sonnet 5 API is an agentic, multimodal interface delivering near-Opus performance with native computer use and self-verification capabilities. It features granular "Effort Levels," allowing', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1782886691046_3pnO8Z4Z.png', 'chat', 'active', 10, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-2.5-flash', 'Gemini 2.5 Flash', 'Gemini 2.5 Flash API is first hybrid reasoning LLM developed by Google DeepMind, built for developers to combine fast generation with optional reasoning for both simple and complex tasks.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1768383901134_aRmGDQKh.webp', 'chat', 'active', 11, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-2.5-pro', 'Gemini 2.5 Pro', 'Gemini 2.5 Pro is Google’s advanced thinking model designed for complex reasoning, code generation and long-context understanding. It supports native multimodal inputs and a context window of up to 1 ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1767689314658_efHZrE72.webp', 'chat', 'active', 12, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-3-flash', 'Gemini 3 Flash', 'Gemini 3 Flash is a high-performance large language model developed by Google DeepMind, designed to deliver frontier-level reasoning with low latency and high throughput. It demonstrates strong perfor', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1768544668909_iLOzTwUf.png', 'chat', 'active', 13, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-3-pro', 'Gemini 3 Pro', 'Gemini 3 Pro API is Google DeepMind’s next-generation multimodal model that delivers advanced reasoning, seamless text-image-video-audio understanding, and large-scale long-context processing.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1763605293713_H2sVHGOl.png', 'chat', 'active', 14, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-3-1-pro', 'Gemini 3.1 Pro', 'Gemini 3.1 Pro API is the latest general-purpose LLM developed by Google DeepMind, designed to bridge the gap between high-speed execution and deep logic. It empowers developers to build sophisticated', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1772448826465_BDSw4GRN.png', 'chat', 'active', 15, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-3-5-flash', 'Gemini 3.5 Flash', 'Gemini 3.5 Flash is Google’s high-efficiency multimodal model, combining Flash-level speed with stronger coding, reasoning, and agentic execution for complex AI workflows that need both capability and', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1780041602634_ga1twkjx.webp', 'chat', 'active', 16, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gpt-5-2', 'GPT-5.2', 'GPT-5.2 is OpenAI’s most advanced GPT-5 model for reasoning, coding, long documents, and professional AI workflows.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1767682377885_7wnpnoLw.webp', 'chat', 'active', 17, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gpt-5-4', 'GPT-5.4', 'OpenAI''s GPT-5.4 delivers powerful capabilities in complex reasoning, coding, and professional knowledge work. It enables faster development cycles, more reliable task execution, and higher quality re', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1773208667333_hxhGjrpf.webp', 'chat', 'active', 18, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gpt-5-5', 'GPT-5.5', 'GPT-5.5 is OpenAI’s advanced reasoning model for agentic coding, knowledge work, scientific research, and complex multi-step task execution.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1777014349580_f1nAuAUc.webp', 'chat', 'active', 19, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gpt-5-6', 'GPT-5.6', 'GPT-5.6 unites Sol, Terra, and Luna in a three-tier family built for frontier intelligence, efficient everyday work, and fast high-volume execution across technical and professional tasks.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1783661548081_mQP8PJ8b.png', 'chat', 'active', 20, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('codex', 'OpenAI Codex', 'OpenAI Codex API delivers advanced coding capabilities built on GPT-5 Codex models. It supports code generation, debugging, and complex engineering workflows with scalable reasoning depth.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1772518049462_FJ4Vqdwe.png', 'chat', 'active', 21, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('grok-4-3', 'Grok 4.3', 'The xAI Grok 4.3 API is advanced flagship reasoning infrastructure, leading the industry in non-hallucination rates, instruction execution, and autonomous tool calling. Supporting text and image multi', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1783506167073_KcF1s2E3.png', 'chat', 'active', 22, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('grok-4-5', 'Grok 4.5', 'Grok 4.5 is xAI’s latest frontier AI model built for coding, agentic tasks, and knowledge work. It delivers strong software engineering capabilities, advanced reasoning, fast inference, and efficient ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/tools/example/1783566829620_Hq91q4ra.png', 'chat', 'active', 23, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gpt-image-2', 'GPT Image 2', 'GPT Image 2 is OpenAI’s next-gen image model built for stronger photorealism, cleaner image editing, sharper text rendering, and more polished product photography. Designed for more advanced visual wo', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1776822371390_vcAYOY4s.webp', 'image', 'active', 24, 0, 1);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('flux-2', 'FLUX 2', 'Flux 2 is Black Forest Labs’ advanced image generation model that delivers photoreal detail, strong multi-reference consistency, and accurate text rendering with flexible control.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1764248320029_qLjs2dCu.png', 'image', 'active', 25, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('flux-kontext-api', 'Flux Kontext', 'In a world where visuals drive engagement, FLUX.1 Kontext API on Kie.ai empowers you to edit images like never before. Harness cutting-edge AI to transform photos with simple text commands, delivering', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760432961990rfe43tz2.png', 'image', 'active', 26, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedream', 'Seedream 3.0', 'Seedream 3.0 API is ByteDance’s latest text-to-image API, built for native 2K resolution, faster generation, and precise bilingual text rendering. Compared to Seedream 2.0, the Seedream v3 API deliver', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/17604336223654bm85hvx.png', 'image', 'active', 27, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedream-api', 'Seedream 4.0', 'Seedream 4.0 API from ByteDance is a next-generation model that combines text-to-image, image-to-image, and editing with batch consistency, high speed, and professional-quality outputs.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/17604346335909arn4y6a.webp', 'image', 'active', 28, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedream-4-5', 'Seedream 4.5', 'Seedream 4.5 is Bytedance’s refined image model for 4K generation, precise editing, and consistent multi-image output.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1764900762655_tyWp22vk.webp', 'image', 'active', 29, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedream5-0-lite', 'Seedream 5.0 Lite', 'Seedream 5.0 Lite is a unified multimodal image generation model by ByteDance, designed for multimodal reasoning, deep understanding, and controllable visual creation. It supports text-to-image and im', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1772007488171_Kk3CSjow.png', 'image', 'active', 30, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedream-5-0-pro', 'Seedream 5.0 Pro', 'Seedream 5.0 Pro is ByteDance’s multimodal image model for controlled generation, precision editing, complex information visualization, realistic portraits, and multilingual visual creation.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1783576840914_q2FEdx8j.png', 'image', 'active', 31, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('google-imagen4', 'Imagen 4', 'Google Imagen 4, developed by Google DeepMind and introduced at Google I/O 2025, is a state-of-the-art text-to-image generation model that transforms prompts into photorealistic, high-quality visuals ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760435085346iwop02tf.webp', 'image', 'active', 32, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('nano-banana-2', 'Nano Banana 2', 'Meet Nano Banana 2, Google’s Gemini 3.1 Flash Image model, now available via Kie AI API. Built for developers, it combines lightning-fast speed with Pro-level quality, accurate text rendering, strong ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1772166557697_MR5wMR3x.png', 'image', 'active', 33, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('nano-banana-2-lite', 'Nano Banana 2 Lite', 'Nano Banana 2 Lite, aka Gemini 3.1 Flash-Lite Image, is a newly released image model from Google DeepMind built for fast 1K image generation, efficient creative iteration, prompt-based image editing, ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1782889892839_kN2Wvt8b.png', 'image', 'active', 34, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('nano-banana-pro', 'Nano Banana Pro', 'Google DeepMind’s Nano Banana Pro delivers sharper 2K imagery, intelligent 4K scaling, improved text rendering, and enhanced character consistency—offering a major leap in visual quality for creative ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1763724737745_iMOlYShq.png', 'image', 'active', 35, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('nano-banana', 'NanoBanana (Gemini 2.5 Flash Image Preview)', 'Gemini 3 Image Preview (aka Nano Banana) is an advanced AI model excelling in natural language-driven image generation and editing. It produces hyper-realistic, physics-aware visuals with seamless sty', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/176043358319433328iqf.png', 'image', 'active', 36, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('ideogram-character', 'Ideogram Character', 'Ideogram Character is the latest feature released by Ideogram AI, ensuring characters retain core features such as facial traits, proportions, and hairstyles across different scenes, artistic styles, ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760434830700wqw6xlbh.png', 'image', 'active', 37, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('ideogram-v3', 'Ideogram V3', 'Ideogram V3 API is the latest generation of Ideogram’s image generation model, offering text-to-image, image editing, reframing, and remixing with improved consistency and creative control.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760434993367qdfpwl8y.webp', 'image', 'active', 38, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('4o-image-api', '4o Image (GPT-4o Image)', 'The GPT-Image-1 model, also known as ChatGPT 4o Image, is OpenAI’s latest AI image generation model. It understands both text and visual context, allowing developers to create and edit images with rem', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/17604329349269y2j98mv.png', 'image', 'active', 39, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gpt-image-1.5', 'GPT Image 1.5', 'GPT Image 1.5 is OpenAI’s flagship image generation model for high-quality image creation and precise image editing, with strong instruction following and improved text rendering.', 'https://kie.ai/cdn-cgi/image/width=1920,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/tools/example/1765961172105_jRGzhUQE.webp', 'image', 'active', 40, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('qwen-image', 'Qwen Image', 'The Qwen Image API empowers creators, developers, and businesses to generate and edit photorealistic images effortlessly. Whether you''re crafting intricate designs or refining existing visuals, this p', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760433599320dsgya6hv.png', 'image', 'active', 41, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('qwen-image-2', 'Qwen Image 2.0', 'Alibaba Qwen Image 2.0 is a unified image model for realistic generation, structured text rendering, native 2K output, and flexible editing across creative and visual design workflows.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1773624843072_OvX6TKSC.png', 'image', 'active', 42, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('qwen-image-edit', 'Qwen Image Edit', 'Qwen-Image-Edit is an open-source image editing model based on Qwen-Image, supporting semantic and appearance editing with precise, visually coherent results. It also handles bilingual (Chinese and En', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760433511788x6nqijt3.png', 'image', 'active', 43, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('z-image', 'Z-Image', 'Z-Image is Tongyi-MAI’s efficient image generation model that delivers photorealistic output, fast Turbo performance, and accurate bilingual text rendering with strong semantic understanding.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1764668121857_aFTwunEO.webp', 'image', 'active', 44, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('recraft-crisp-upscale', 'Recraft Crisp Upscale', 'Transform blurry photos into crystal-clear masterpieces using the Recraft Crisp Upscale API. As the ultimate free image upscaler, this tool leverages advanced AI to deliver professional-grade results ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/17604347566588mjtbog0.webp', 'image', 'active', 45, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('recraft-remove-background', 'Recraft Remove Background', 'Built by Recraft AI, the Remove Background API accurately separates subjects from any background and delivers clean, transparent outputs—optimized for seamless integration into websites, eCommerce pla', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760434543121linen0ej.png', 'image', 'active', 46, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('topaz-image-upscale', 'Topaz Image Upscale', 'Topaz Labs Image Upscale is an AI image enhancement model that increases resolution and restores detail with high-fidelity upscaling, natural texture reconstruction, and improved clarity across low-qu', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1763435260839_zZ9NIgks.png', 'image', 'active', 47, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-2-7-image', 'Wan2.7 Image', 'Wan2.7-Image is Alibaba’s unified image model family for generation and editing, supporting text-to-image, image editing, advanced text rendering, multi-image workflows, 2K output in its standard vari', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1775115239124_hXRRIIrJ.webp', 'image', 'active', 48, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('veo-3-1', 'Veo 3.1', 'Google DeepMind’s upgraded AI video model for realistic motion generation, extended clip duration, multi-image reference control, and synchronized audio output in native 1080p.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 49, 0, 1);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-3-0', 'Kling 3.0', 'Kling 3.0 is Kling AI’s video generation model that creates videos from text and images, supports multi-shot storytelling, and produces native audio with cinematic control up to 15 seconds.', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 50, 0, 1);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedance-2-5', 'Seedance 2.5', 'Seedance 2.5 is ByteDance’s upgraded AI video model, designed for 30-second generation, native 4K output, multimodal reference control, precise local edits, and more production-ready creative workflow', 'https://placehold.co/80x80/8b5cf6/ffffff?text=S', 'video', 'active', 51, 1, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('happyhorse-1-0', 'HappyHorse-1.0', 'HappyHorse-1.0 is an emerging AI video model developed by Alibaba ATH and has quickly become one of the most watched new names in AI video generation. It is associated with strong text-to-video and im', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 52, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('happyhorse-1-1', 'HappyHorse-1.1', 'HappyHorse-1.1 is an AI video generation model that improves on HappyHorse-1.0 with better prompt understanding, smoother motion, stronger consistency, and higher-quality outputs across T2V, I2V, and ', 'https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'video', 'active', 53, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('omnihuman-1-5', 'OmniHuman 1.5', 'OmniHuman 1.5 is ByteDance''s AI avatar and digital human model that transforms a single image and audio into realistic talking videos with natural lip sync, facial expressions, and lifelike motion.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1781519396920_v6WZVKQQ.png', 'video', 'active', 54, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedance-1-0-pro-fast', 'Seedance 1.0 Pro Fast', 'ByteDance’s AI video-generation model that inherits Seedance 1.0 Pro’s core quality while delivering 3× faster rendering, producing coherent 1080p clips with stable motion and efficient compute perfor', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 55, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedance-1-5-pro', 'Seedance 1.5 Pro', 'Seedance 1.5 Pro is ByteDance’s audio-video generation model that creates cinema-quality video, synchronized audio, and multilingual dialogue with cinematic camera control.', 'https://static.aiquickdraw.com/aa/kie-maket/1783576840914_q2FEdx8j.png', 'video', 'active', 56, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedance-2-0', 'Seedance 2.0', 'Seedance 2.0 on KIE is a multimodal Al video model by ByteDance, optimized for fast and realistic video generation. It supports high-quality virtual human video creation with strong multi-shot consist', 'https://file.aiquickdraw.com/static//kie-maket/1760433549799kz5yzjvx.png', 'video', 'active', 57, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('seedance-2-0-mini', 'Seedance 2.0 Mini', 'Seedance 2.0 Mini is ByteDance''s cost-efficient AI video model designed for faster generation and lower inference costs. It supports text-to-video, image-to-video, consistent character generation, and', 'https://static.aiquickdraw.com/aa/kie-maket/1783576840914_q2FEdx8j.png', 'video', 'active', 58, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('bytedance-seedance-v1', 'Seedance V1', 'From Seeds of Ideas to Dancing Visuals: Seedance 1.0 API Brings Your Stories to Life', 'https://placehold.co/80x80/8b5cf6/ffffff?text=S', 'video', 'active', 59, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('volcengine-video-to-video-lip-sync', 'Volcengine Lip Sync', 'Make every frame speak your language — Volcengine Lip Sync API delivers pixel-perfect video-to-video lip sync and AI dubbing in minutes.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1781657706996_r4GY3UUZ.png', 'video', 'active', 60, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-omni', 'Gemini Omni', 'Gemini Omni is Google’s released multimodal creation model built to create from different kinds of input, starting with video. Gemini Omni Flash is the first model in the Omni family, supporting pract', 'https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'video', 'active', 61, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('features-v3-api', 'Veo 3', 'Google Veo 3 is a next-generation AI video generation model developed by Google DeepMind. It supports both text-to-video and image-to-video creation, producing high-fidelity, cinematic visuals with ad', 'https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'video', 'active', 62, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-2-5', 'Kling 2.5 Turbo', 'Kling 2.5 Turbo is the latest AI video generation model from Kuaishou Kling, designed for text-to-video and image-to-video creation. Compared to earlier versions, it features better prompt adherence, ', 'https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'video', 'active', 63, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-2-6', 'Kling 2.6', 'Kling 2.6 is Kling AI’s audio-visual generation model that produces synchronized video, speech, ambient sound, and sound effects from text or image inputs.', 'https://file.aiquickdraw.com/static//kie-maket/1760433549799kz5yzjvx.png', 'video', 'active', 64, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-2.6-motion-control', 'Kling 2.6 Motion Control', 'Developed by KuaiShou, Kling AI 2.6 Motion Control API is a performance-driven image-to-video model that transfers real human motion, gestures, and expressions from reference video to character images', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 65, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-3-motion-control', 'Kling 3.0 Motion Control', 'Kling Motion Control 3.0 is Kuaishou Kling’s AI video motion model that transfers movement from reference videos to character images while preserving facial identity, expressions, and realistic motion', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 66, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-3-0-turbo', 'Kling 3.0 Turbo', 'Kling 3.0 Turbo is Kuaishou’s faster video generation model in the Kling 3.0 series, built to balance high-quality visuals, smooth motion, prompt adherence, multi-shot continuity, precise audio-visual', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 67, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-ai-avatar', 'Kling AI Avatar 2.0', 'Kling AI Avatar 2.0 is Kuaishou’s audio-driven avatar model that transforms a single image and voice into expressive talking videos, supporting multilingual speech and up to five-minute continuous gen', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/17619663858536k4b38ze.png', 'video', 'active', 68, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('kling-v2-1', 'Kling V2.1', 'The Kling 2.1 model powers cutting-edge video generation with hyper-realistic motion, advanced physics, and high-resolution outputs up to 1080p. Its enhanced semantic understanding and fast rendering ', 'https://placehold.co/80x80/ef4444/ffffff?text=K', 'video', 'active', 69, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('hailuo-api', 'Hailuo 02', 'Hailuo 02 API is Minimax’s advanced AI video generation model that turns text or images into short, cinematic clips. It supports high-quality output up to 1080P, with realistic motion, physics simulat', 'https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'video', 'active', 70, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('hailuo-2-3', 'Hailuo 2.3', 'Hailuo 2.3 is MiniMax’s high-fidelity AI video generation model designed to create realistic motion, expressive characters, and cinematic visuals. It supports both text-to-video and image-to-video, ha', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 71, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('infinitalk', 'InfiniteTalk', 'InfiniteTalk API is an advanced AI lip sync video API developed by MeiGen-AI. It transforms images or text with audio into natural talking avatars, offering precise lip synchronization, expressive fac', 'https://placehold.co/80x80/6b7280/ffffff?text=I', 'video', 'active', 72, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('runway-api', 'Runway Gen-4', 'Step into the future of content creation with the Runway API, powered by Runway AI''s groundbreaking Gen-4 architecture. Available exclusively through Kie.ai, this toolkit transforms ideas into stunnin', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/custom-page/akr/section-images/1760352550893x3wzqgla.webp', 'video', 'active', 73, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('topaz-video-upscaler', 'Topaz Video Upscaler', 'Topaz Video Upscaler API delivers professional-grade AI video enhancement, restoring detail, reducing noise, and providing high-quality upscaling to 1080p or 4K.', 'https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'video', 'active', 74, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-speech-to-video-turbo', 'Wan 2.2 A14B Speech to Video Turbo', 'Wan 2.2 A14B Turbo API Speech to Video, this revolutionary AI model turns static images and audio clips into dynamic, expressive videos, perfect for creators, marketers, and educators. Available now o', 'https://placehold.co/80x80/06b6d4/ffffff?text=W', 'video', 'active', 75, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-animate', 'Wan 2.2 Animate', 'Wan 2.2 Animate API by Alibaba’s Tongyi Lab generates realistic character videos with motion, expressions, and lighting. It supports animation mode for driving static images and replacement mode for s', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 76, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-2-5', 'Wan 2.5', 'Wan 2.5 API from Alibaba is designed for cinematic AI video generation, supporting both text-to-video (wan2.5-t2v-preview) and image-to-video (wan2.5-i2v-preview). It natively synchronizes visuals wit', 'https://static.aiquickdraw.com/aa/kie-maket/1775115239124_hXRRIIrJ.webp', 'video', 'active', 77, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-2-6', 'Wan 2.6', 'Wan 2.6 is Alibaba’s latest AI video model, offering affordable multi-shot 1080p generation with stable characters and synchronized native audio. Through the Wan 2.6 API—including T2V, I2V, and refere', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 78, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-2-7-video', 'Wan 2.7 Video', 'Wan 2.7 Video API is Alibaba Tongyi Lab''s AI video suite, covering four generation modes — Text-to-Video, Image-to-Video, Reference-to-Video, and Video Edit. It supports full-modality input (text, ima', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1775570986415_ghhtjD4T.png', 'video', 'active', 79, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('wan-v2-2', 'Wan V2.2 A14B', 'Wan 2.2 A14B Turbo API, the latest generation of the Wan video model, is built with a Mixture-of-Experts (MoE) architecture and supports text-to-video (T2V), image-to-video (I2V) and speech-to-video(S', 'https://placehold.co/80x80/06b6d4/ffffff?text=W', 'video', 'active', 80, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('grok-imagine', 'Grok Imagine', 'Grok Imagine is xAI’s AI video generation model for creating high-quality videos with realistic motion, native audio, and synchronized speech. Grok Imagine 1.5 introduces faster generation speeds, imp', 'https://static.aiquickdraw.com/aa/kie-maket/1783506167073_KcF1s2E3.png', 'video', 'active', 81, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('grok-imagine-video-1.5', 'Grok Imagine Video 1.5', 'Grok Imagine Video 1.5 is xAI''s AI video generation model that creates realistic videos, generates synchronized audio, and supports video editing workflows with strong prompt adherence and consistent ', 'https://file.aiquickdraw.com/static//kie-maket/1760602507559tkxwc40s.png', 'video', 'active', 82, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('elevenlabs-text-to-dialogue-v3', 'ElevenLabs Text to Dialogue V3', 'ElevenLabs Eleven V3 enables expressive multilingual Text to Dialogue with audio tag control, multi-speaker support, and natural delivery, designed for dialogue-driven applications, storytelling tools', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1768557100213_oAru1Ofg.png', 'audio', 'active', 83, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('elevenlabs-tts', 'ElevenLabs TTS', 'Elevate your content with the ElevenLabs API text to speech, delivering human-like audio that captivates audiences. At Kie.ai, access ElevenLabs TTS API effortlessly for podcasts, apps, and more – no ', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760433667541h7dtoy2i.png', 'audio', 'active', 84, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-2.5-pro-preview-tts', 'Gemini 2.5 Pro Preview TTS', 'Gemini 2.5 Pro Preview TTS is Google’s premium text-to-speech model designed for studio-quality, high-fidelity audio generation. It enables developers to create realistic AI voices with natural langua', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/tools/example/1784268770224_M2jcs7BV.png', 'audio', 'active', 85, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('gemini-3.1-flash-tts', 'Gemini 3.1 Flash TTS', 'Gemini 3.1 Flash TTS Preview is an expressive text-to-speech model by Google that delivers natural AI voice generation with advanced control over tone, emotion, pacing, and speaking style.', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://static.aiquickdraw.com/aa/kie-maket/1784273103040_USqy563j.png', 'audio', 'active', 86, 0, 0);
INSERT OR REPLACE INTO ai_models (id, name, description, icon, category, status, sort_order, is_new, is_hot) VALUES ('suno-api', 'Suno V5.5', 'Kie AI Music API is an AI music-generation model that converts text prompts into full vocal and instrumental tracks with natural dynamics and coherent musical progression, and it currently supports th', 'https://kie.ai/cdn-cgi/image/width=1080,quality=85,fit=scale-down,format=webp/https://file.aiquickdraw.com/static//kie-maket/1760433549799kz5yzjvx.png', 'audio', 'active', 87, 0, 0);